### ISSUE TITLE
Spammers use https://adguardteam.github.io/AnonymousRedirect/redirect.html as open redirect

### ISSUE THREAD

**Issue by igor-ye** [AdguardTeam/AnonymousRedirect#5]
Recently I found tens of thousands links in Google Search Console with targets like this:
https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://bawang.se/mens-fashion-t-shirts/men-s-double-faced-sweater--904000581258692.html

Linking site #1:
![image](https://user-images.githubusercontent.com/1421072/81149220-d632c180-8f8e-11ea-80ad-500674395aa6.png)

Linking site #2:
![image](https://user-images.githubusercontent.com/1421072/81149258-ed71af00-8f8e-11ea-8768-f5f8c0ae0b98.png)

A lot of such linking sites:
![image](https://user-images.githubusercontent.com/1421072/81149349-17c36c80-8f8f-11ea-8aed-b7a3e8894ae9.png)

You should definitely remove page with open redirect from https://adguardteam.github.io/AnonymousRedirect/redirect.html as it's used by spammers to cloak redirects to their sites.

**Comment by ameshkov** [comment]
Anyone can easily clone this repo and set up the very same redirect page, it's just a couple of JS lines. Also, there are tons of legit links that will be broken in this case.

Could you please elaborate? What's the problem with them using this page? How's that different from spamming direct links?

I guess as a temporary solution we could change that page so that the redirect was not automatic, and the user needed to click one more time to get to the target page.

**Comment by ameshkov** [comment]
Done, check the updated page:
https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.whatismyreferer.com/
